package com.gaohx.springbootlearningjdbc.model;

import java.math.BigDecimal;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CITY.ID
     *
     * @mbg.generated Tue Nov 13 11:36:04 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CITY.NAME
     *
     * @mbg.generated Tue Nov 13 11:36:04 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CITY.ID
     *
     * @return the value of T_CITY.ID
     *
     * @mbg.generated Tue Nov 13 11:36:04 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CITY.ID
     *
     * @param id the value for T_CITY.ID
     *
     * @mbg.generated Tue Nov 13 11:36:04 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CITY.NAME
     *
     * @return the value of T_CITY.NAME
     *
     * @mbg.generated Tue Nov 13 11:36:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CITY.NAME
     *
     * @param name the value for T_CITY.NAME
     *
     * @mbg.generated Tue Nov 13 11:36:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}