package com.gaohx.springbootlearningjdbc.dao;

import com.gaohx.springbootlearningjdbc.model.Role;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat May 25 13:14:18 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat May 25 13:14:18 CST 2019
     */
    int insertSelective(Role record);
}